### ISSUE TITLE
Python Error on Date Format When Accessing UP42 Console

### ISSUE THREAD

**Issue by santisoto77** [Kan-T-IT/QGIS-KICa#38]
Description:
Clicking the button to access the UP42 console triggers a Python error related to the date format.

Steps to Reproduce:

Log in to the application.
Navigate to the section where the UP42 console button is available.
Click the button to open the UP42 console.
Expected Behavior:
The UP42 console should load successfully without any errors.

Actual Behavior:
A Python error occurs, indicating an issue with the date format. The console fails to load.

Logs/Error Message:
`2024-12-20T12:38:31 WARNING Traceback (most recent call last): File "/Users/diego.alarcon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kan_imagery_catalog/gui/custom_widgets.py", line 122, in download_images download_url, params = catalogs.get_download_url(**data) File "/Users/diego.alarcon/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kan_imagery_catalog/core/catalogs.py", line 267, in get_download_url start_date = datetime.strptime(str_start_date, '%Y-%d-%m') - timedelta(days=1) File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/_strptime.py", line 352, in _strptime raise ValueError("unconverted data remains: %s" % ValueError: unconverted data remains: 3`

**Comment by PelJon** [comment]
The issue is not resolved when I tested it with Version 1.61. - I receive the following error code:

```
2025-01-23T16:07:50     WARNING    Traceback (most recent call last):
              File "/Users/pelle-svante.john/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kan_imagery_catalog/gui/custom_widgets.py", line 122, in download_images
              download_url, params = catalogs.get_download_url(**data)
              File "/Users/pelle-svante.john/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kan_imagery_catalog/core/catalogs.py", line 267, in get_download_url
              start_date = datetime.strptime(str_start_date, '%Y-%m-%d') - timedelta(days=1)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/_strptime.py", line 568, in _strptime_datetime
              tt, fraction, gmtoff_fraction = _strptime(data_string, format)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/_strptime.py", line 352, in _strptime
              raise ValueError("unconverted data remains: %s" %
             ValueError: unconverted data remains: 5
```

**Comment by PelJon** [comment]
Can not reproduce anymore with latest version, can be closed.

**Comment by santisoto77** [comment]
It closes as the error is not reproduced
